jobs:
  buildCE:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: init mysql
      run: 'sudo /etc/init.d/mysql start

        export MYSQL_PWD=root

        for i in */*.sql;do echo $i;mysql -h localhost -uroot < $i;done

        '
      working-directory: support-files/sql
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Cache Gradle
      uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        path: ~/.gradle/caches
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: Gradle Build
      run: ./gradlew clean build -DmysqlURL=127.0.0.1:3306 -DmysqlUser=root -DmysqlPasswd=root
        -DmavenRepoUrl="https://mirrors.cloud.tencent.com/nexus/repository/maven-public/"
      working-directory: src/backend
  buildEE:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: init mysql
      run: 'sudo /etc/init.d/mysql start

        export MYSQL_PWD=root

        for i in */*.sql;do echo $i;mysql -h localhost -uroot < $i;done

        '
      working-directory: support-files/sql
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Cache Gradle
      uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        path: ~/.gradle/caches
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: Gradle Build
      run: ./gradlew clean build -DmysqlURL=127.0.0.1:3306 -DmysqlUser=root -DmysqlPasswd=root
        -DmavenRepoUrl="https://mirrors.cloud.tencent.com/nexus/repository/maven-public/"
        -Pjob.edition=ee -Pjob.package.type=release
      working-directory: src/backend
name: Backend CI
on:
  repository_dispatch:
    types: trigger-ga___backend.yml
