jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      run: echo "npm version=$(npm -v)"
    - continue-on-error: true
      name: build
      run: 'export JOB_VERSION=3.latest

        npm i --legacy-peer-deps && npm run build

        '
      working-directory: src/frontend
name: Frontend CI
on:
  repository_dispatch:
    types: trigger-ga___frontend.yml
